### PR TITLE
Example of synchronous error handling

### LINKED ISSUE #105: Make sample that has both synchronous and asynchronous exceptions
SYCL code can have both synchronous and asynchronous exceptions. While our samples very well demonstrate async handlers, errors that happen synchronously are exhibited less, and are dealt with even more poorly. To that end we should add a sample that shows some of the ways that synchronous exceptions can be thrown (e.g. a device selector that returns a negative number for all devices, contexts constructed from invalid OpenCL contexts - there are lots of possibilities).

### PR DESCRIPTION
**Pull request by RossBrunton**
This example is specifically about a handler which fails to find a valid
device.

This should fix #105.

----

Once again, let me know if I'm not writing my code "sycl-y" enough, or you want another example with the CL context thing.

### CODE REVIEW

File: samples/sync-handler/sync-handler.cpp [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+    buffer<size_t, 1> buf(sevens.data(), range<1>(number_of_sevens));
+    myQueue.submit([&](handler& cgh) {
+      auto ptr = buf.get_access<access::mode::discard_write>(cgh);
+      cgh.parallel_for<Worker>(range<1>(number_of_sevens),
+                               [=](item<1> item) { ptr[item] = 7; });
+    });
+  } catch (exception const& e) {
+    /* Report the exception to the user. */
+    std::cout << "SYCL exception caught: " << e.what() << "\n";
+    std::cout << "Running on host...\n";
```
Comment (cjdb) [inline samples/sync-handler/sync-handler.cpp]: These ought to be writes to `cerr`, rather than `cout`.

File: samples/sync-handler/sync-handler.cpp [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+
+    /* If the selector couldn't find a suitable device, the following code
+     * will not run. */
+    buffer<size_t, 1> buf(sevens.data(), range<1>(number_of_sevens));
+    myQueue.submit([&](handler& cgh) {
+      auto ptr = buf.get_access<access::mode::discard_write>(cgh);
+      cgh.parallel_for<Worker>(range<1>(number_of_sevens),
+                               [=](item<1> item) { ptr[item] = 7; });
+    });
+  } catch (exception const& e) {
```
Comment (cjdb) [inline samples/sync-handler/sync-handler.cpp]: Please choose one of east-`const` or `const`-west per file. I recommend east-`const`, since that means that your `const` is always to the right of whatever you want to `const`-qualify.

File: samples/sync-handler/sync-handler.cpp [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+ **************************************************************************/
+
+#include <CL/sycl.hpp>
+
+#include <iostream>
+
+using namespace cl::sycl;
+
+namespace {
+class Worker;
```
Comment (cjdb) [inline samples/sync-handler/sync-handler.cpp]: This is a declaration. IIRC we need this to be a definition (cc @Ruyk).
